import requests
import os

SEARCH_API_KEY = os.getenv('SEARCH_API_KEY')
SEARCH_ENGINE_ID = os.getenv('SEARCH_ENGINE_ID')

search_url = "https://www.googleapis.com/customsearch/v1"


def google_search(search_term, **kwargs):
    return [{'kind': 'customsearch#result',
             'title': 'The ENEMY Has Gun | How did i Win this? | PUBG MOBILE',
             'htmlTitle': 'The ENEMY Has Gun | How did i Win this? | <b>PUBG</b> MOBILE',
             'link': 'https://www.google.com/news/url?url=https://trends.gb.net/view/2867Frw6N1w',
             'displayLink': 'www.google.com',
             'snippet': 'Fanpage Tacaz ✌ Follow me on Facebook My setting: Handcam Video: Hit that \nlike button and Subscribe if you liked the video! Comment what type of video you\n\xa0...',
             'htmlSnippet': 'Fanpage Tacaz ✌ Follow me on Facebook My setting: Handcam Video: Hit that <br>\nlike button and Subscribe if you liked the video! Comment what type of video you<br>\n&nbsp;...',
             'cacheId': 'Jl_JkzRctPUJ',
             'formattedUrl': 'https://www.google.com/news/url?url=https://trends.gb.net/view/...',
             'htmlFormattedUrl': 'https://www.google.com/news/url?url=https://trends.gb.net/view/...',
             'pagemap': {'cse_thumbnail': [{
                 'src': 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSy5-3hclsQgZnG6zIOyDU6rd5CXwHlRCUVUW2lQQPsjfvFoxhlhZaFcBM',
                 'width': '259',
                 'height': '194'}],
                 'metatags': [{'og:image': 'https://i.ytimg.com/vi/2867Frw6N1w/hqdefault.jpg',
                               'og:type': 'video',
                               'twitter:card': 'summary_large_image',
                               'og:site_name': 'trending',
                               'handheldfriendly': 'True',
                               'msvalidate.01': '90D24C694453A2A855B1805E06DDF076',
                               'viewport': 'width=device-width, initial-scale=1.0',
                               'og:title': 'The ENEMY Has Gun | How did i Win this? | PUBG MOBILE',
                               'yandex-verification': 'f0b7c087518eb76b',
                               'hilltopads-site-verification': 'aee64931d0795e894809b62d0a340d9d2c0bd469',
                               'og:url': 'https://trends.gb.net/view/2867Frw6N1w',
                               'og:description': '🤞Fanpage Tacaz  ✌ Follow me on Facebook  My setting:  Handcam Video:  Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how to, weapon challenge, world record, trick shot or high kill gameplay) My setting:  Handcam Video:  Played on...'}],
                 'videoobject': [{'duration': 'PT25M9S',
                                  'embedurl': 'https://www.youtube.com/embed/2867Frw6N1w',
                                  'uploaddate': '2020-01-23T12:00:00.000Z',
                                  'name': 'The ENEMY Has Gun | How did i Win this? | PUBG MOBILE',
                                  'description': '🤞Fanpage Tacaz ✌ Follow me on Facebook My setting: Handcam Video: Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how...',
                                  'url': 'https://trends.gb.net/view/2867Frw6N1w',
                                  'thumbnailurl': 'https://i.ytimg.com/vi/2867Frw6N1w/hqdefault.jpg'}],
                 'cse_image': [{'src': 'https://i.ytimg.com/vi/2867Frw6N1w/hqdefault.jpg'}],
                 'listitem': [{'image': 'https://i.ytimg.com/vi/BhTc9zMwU1w/mqdefault.jpg',
                               'name': 'Throwing NADE IQ 1000!! | Tacaz is King of Nade | PUBG MOBILE',
                               'description': '🤞Fanpage Tacaz ✌ Follow me on Facebook My setting: Handcam Video: Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how...',
                               'position': '1',
                               'url': 'Throwing NADE IQ 1000!! | Tacaz is King of Nade | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/CynzBpfN1rg/mqdefault.jpg',
                               'name': 'BEST AKM GAMEPLAY | 33 KILLS SOLO VS SQUAD | PUBG MOBILE',
                               'description': 'Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how to, weapon challenge, world record, trick shot or high kill gameplay)...',
                               'position': '2',
                               'url': 'BEST AKM GAMEPLAY | 33 KILLS SOLO VS SQUAD | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/wZKoA3XxeCo/mqdefault.jpg',
                               'name': 'NERF GUN GAME 12.0 (Nerf First Person Shooter!)',
                               'description': 'A Nerf War meets Call of Duty: Gun Game 12.0 with Fortnite blasters, Overwatch guns and much more! First person through all 20 weapons wins the battle! Good luck! Featuring these epic Nerf...',
                               'position': '3',
                               'url': 'NERF GUN GAME 12.0 (Nerf First Person Shooter!)'},
                              {'image': 'https://i.ytimg.com/vi/PD2Jk8BRhZw/mqdefault.jpg',
                               'name': 'Fortnite - Perfect Timing Moments #75 (Chapter 2)',
                               'description': "🎬Submit Your Clips: Hey there, Welcome Back to, the greatest multi-game community montages on YouTube! On Elegance you'll find all the greatest fortnite perfect timing clips creative and...",
                               'position': '4',
                               'url': 'Fortnite - Perfect Timing Moments #75 (Chapter 2)'},
                              {'image': 'https://i.ytimg.com/vi/m5yelSpKdZQ/mqdefault.jpg',
                               'name': 'When Pubg Takes On Tiktok Most Funny Pubg Tiktok Video || Pubg Moments On Tiktok Episode #11 || WTF',
                               'description': 'Hey this is THE VYPER GAMER & This video is about Pubg Tiktok videos, PUBG MOBILE. ★★★ FOLLOW ME ★★★ 📍 Twitter : 📍 Instagram: 📍Facebok : My business email : najrulraja2016@gmai...',
                               'position': '5',
                               'url': 'When Pubg Takes On Tiktok Most Funny Pubg Tiktok Video || Pubg Moments On Tiktok Episode #11 || WTF'},
                              {'image': 'https://i.ytimg.com/vi/sotGpkv83p8/mqdefault.jpg',
                               'name': 'AWM + M249 VS CAMPER SQUAD!!! | 30 KILLS SOLO VS SQUAD | PUBG MOBILE',
                               'description': 'Get WinZO Gold here : AWM + M249 VS CAMPER SQUAD!!! | 20 KILLS SOLO VS SQUAD | PUBG MOBILE Discord: Share, Support, Subscribe!!! Subscribe: Twitter: Facebook: Instagram: About : Ujjwal Gamer...',
                               'position': '6',
                               'url': 'AWM + M249 VS CAMPER SQUAD!!! | 30 KILLS SOLO VS SQUAD | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/nuQzUcS5Wpg/mqdefault.jpg',
                               'name': 'POWER of MK14 Auto + 6x SCOPE | PUBG MOBILE',
                               'description': '🤞Fanpage Tacaz ✌ Follow me on Facebook My setting: Handcam Video: Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how...',
                               'position': '7',
                               'url': 'POWER of MK14 Auto + 6x SCOPE | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/p9JgmgfnyFo/mqdefault.jpg',
                               'name': '38 KILLS - NEW WORLD RECORD IN SEASON 10 | BEST GROZA SOLO VS SQUAD | PUBG MOBILE',
                               'description': 'Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how to, weapon challenge, world record, trick shot or high kill gameplay)...',
                               'position': '8',
                               'url': '38 KILLS - NEW WORLD RECORD IN SEASON 10 | BEST GROZA SOLO VS SQUAD | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/rWvgIQTQekY/mqdefault.jpg',
                               'name': '9 Enemies VS LEVINHO in same house | PUBG MOBILE',
                               'description': 'Hit that like button and Subscribe if you liked the video! Subscribe to Gazano’s channel : Follow me on Instagram : LevinhoPUBG My settings : Handcam Video : Played on : IPhone XS Max Recording...',
                               'position': '9',
                               'url': '9 Enemies VS LEVINHO in same house | PUBG MOBILE'},
                              {'image': 'https://i.ytimg.com/vi/teNbUlhh02A/mqdefault.jpg',
                               'name': 'NO AMMO!! CAN I WIN LAST GUY WITH A FLARE GUN? | SOLO VS SQUAD PUBG MOBILE',
                               'description': 'Live stream on FB: Hit that like button and Subscribe if you liked the video! Comment what type of video you want next (tips, tricks, how to, weapon challenge, world record, trick shot or high...',
                               'position': '10',
                               'url': 'NO AMMO!! CAN I WIN LAST GUY WITH A FLARE GUN? | SOLO VS SQUAD PUBG MOBILE'}]}},
            {'kind': 'customsearch#result',
             'title': 'PUBG MOBILE - Apps on Google Play',
             'htmlTitle': '<b>PUBG</b> MOBILE - Apps on Google Play',
             'link': 'https://www.google.com/appserve/mkt/p/AEM7UVQe3oNAplwyeNvjt4up4N82tsveIGSgeHmgzhcSS9W35Pqm1WLQJFTvGEjPKAHxOia90nrY_hkYwGQT-eLcSJqBc3Kmw9EHF_JSfBtZCgCW-P2jX4lcaIz8qi4NLqc3Cd7rUN-_uuxFiASzXPJlPrr6OPrDlHc1yBxIBSbZs1qMsdu4IJPUqgIrYlriAuy1IC7stdzV4qq1gmWwzBibCuuVZIDIT_XVCT6bqLzrEKKpc4fCGe6BYwjYLbGknn-cNaKs-J-RRQ1cWo5A5xEbRohQ4fhw53noYi-ftZ0yZNUjHnoDYJ0_WqYw3DOne5tYp-Nj8poP-zm6NL5QUiD9blCQgroYtTzhoqkkRAiM2TW_dQEZSRFyjMiyAu5VUqYGXW14qLSfIKgyp2YsgTYUk6tbGqYeh2YRV8nITFjUTl_LyPUcIFg9S0GAWgVKY2rSvoo87P5Vupo87RELpbWZSCEPNeqxB7psF9t2rQZ6wh_6eDfjRC6ZHTrfcDWqFAWwVuL2WRdYsAVYH2Xz2uwYG_uDB8kxbMyPpdibueR9rw49I_okBGJMHy7sK9ZG8ip-UkxtWpJejIczvKYStcknMs_8holj17PhvqM10SE2mu-dQFJ2JpPbjWcINimE0szqojPbYlZLlTAt16-sWZ3D5rLfkV0Rc2TkoYJtiVkCcWeCQtk3JqJ4Ccmry_d-Ewmk8WdAnNNBEls54D-wcHGaQqHHvYvAjgLeK9DPeqjnZ7-MFGdIcrGrzMMxAPXHnNMT6gDaaRJdy-dXMi6Lnqu2Fq_pXpEKLr70nqJet1-VCEs3TrBQ6YcDqDSYbIdp5Dv76Q',
             'displayLink': 'www.google.com',
             'snippet': "The official PLAYERUNKNOWN'S BATTLEGROUNDS designed exclusively for \nmobile. Play free anywhere, anytime. PUBG MOBILE delivers the most intense\xa0...",
             'htmlSnippet': 'The official PLAYERUNKNOWN&#39;S BATTLEGROUNDS designed exclusively for <br>\nmobile. Play free anywhere, anytime. <b>PUBG</b> MOBILE delivers the most intense&nbsp;...',
             'cacheId': 'mIEEgpUDouwJ',
             'formattedUrl': 'https://www.google.com/.../ AEM7UVQe3oNAplwyeNvjt4up4N82tsveIGSgeHmgzhcSS9W35Pqm1W...',
             'htmlFormattedUrl': 'https://www.google.com/.../ AEM7UVQe3oNAplwyeNvjt4up4N82tsveIGSgeHmgzhcSS9W35Pqm1W...',
             'pagemap': {'offer': [{'price': '0',
                                    'url': 'https://play.google.com/store/apps/details?id=com.tencent.ig&rdid=com.tencent.ig&feature=md&offerId'}],
                         'cse_thumbnail': [{
                             'src': 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRBPXtw5os-OujlO67-CjLwO5Eoao3ZckcMbunlyyfeEFQBPtExTMV_teub',
                             'width': '300',
                             'height': '168'}],
                         'metatags': [{
                             'og:image': 'https://lh3.googleusercontent.com/stoxDZ8vLuvo2d08b_68Oq8Q1xAGWDOF6F3AlwCd1nxeiXcMCwKcjDhasRjyRVUl7HU',
                             'og:type': 'website',
                             'twitter:card': 'summary_large_image',
                             'twitter:title': 'PUBG MOBILE - Apps on Google Play',
                             'twitter:url': 'https://play.google.com/store/apps/details?id=com.tencent.ig&hl=en_US',
                             'appstore:developer_url': 'http://www.pubgmobile.com',
                             'og:title': 'PUBG MOBILE - Apps on Google Play',
                             'twitter:image': 'https://lh3.googleusercontent.com/stoxDZ8vLuvo2d08b_68Oq8Q1xAGWDOF6F3AlwCd1nxeiXcMCwKcjDhasRjyRVUl7HU=w600-h300-pc0xffffff-pd',
                             'appstore:bundle_id': 'com.tencent.ig',
                             'referrer': 'origin',
                             'twitter:site': '@GooglePlay',
                             'appstore:store_id': 'com.tencent.ig',
                             'viewport': 'width=device-width, initial-scale=1',
                             'apple-mobile-web-app-capable': 'yes',
                             'twitter:description': 'The official PLAYERUNKNOWN\'S BATTLEGROUNDS designed exclusively for mobile. Play free anywhere, anytime. PUBG MOBILE delivers the most intense free-to-play multiplayer action on mobile. Drop in, gear up, and compete. Survive epic 100-player classic battles, payload mode and fast-paced 4v4 team deathmatch and zombie modes. Survival is key and the last one standing wins. When duty calls, fire at will!\n\n2018 Mobile Game of the Year – Golden Joystick Award\nBest game, fan favorite games, most competitive games - Google Play 2018 Awards\n\n"Absolutely remarkable" - IGN\n"It\'s awesome." - Pocket Gamer\n"Keeps players coming back" - Vice\n\nFREE ON MOBILE - Powered by the Unreal Engine 4. Play console quality gaming on the go. Delivers jaw-dropping HD graphics and 3D sound. Featuring customizable mobile controls, training modes, and voice chat. Experience the most smooth control and realistic ballistics, weapon behavior on mobile.\n\nMASSIVE BATTLE MAPS - From Erangel to Miramar, Vikendi to Sanhok, compete on these enormou',
                             'mobile-web-app-capable': 'yes',
                             'og:url': 'https://play.google.com/store/apps/details?id=com.tencent.ig&hl=en_US'}],
                         'cse_image': [{
                             'src': 'https://lh3.googleusercontent.com/m92fSnnptC2dLBy4Il1j2WpXt91gCfaW2BchKSvpe09dAUfwCxe4k3blbMkgAUE-lFkA=w500-h280-rw'}]}},
            {'kind': 'customsearch#result',
             'title': 'Pubg qiwi',
             'htmlTitle': '<b>Pubg</b> qiwi',
             'link': 'https://www.google.com/mymaps/viewer?usp=sharing&mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa',
             'displayLink': 'www.google.com',
             'snippet': 'Pubg qiwi → http://catomerra.rusmenik.ru/?dl&keyword=pubg+qiwi&source=\ngmaps Pubg qiwi Looking to trade some of your PUBG Skins? If you are looking \nto\xa0...',
             'htmlSnippet': '<b>Pubg</b> qiwi → http://catomerra.rusmenik.ru/?dl&amp;keyword=<b>pubg</b>+qiwi&amp;source=<br>\ngmaps <b>Pubg</b> qiwi Looking to trade some of your <b>PUBG</b> Skins? If you are looking <br>\nto&nbsp;...',
             'cacheId': '6FCQ1HJY4jAJ',
             'formattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&mid=17F5k...',
             'htmlFormattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&amp;mid=17F5k...',
             'pagemap': {
                 'website': [{'image': 'https://www.google.com/maps/d/thumbnail?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa',
                              'name': 'Pubg qiwi',
                              'description': 'Pubg qiwi → http://catomerra.rusmenik.ru/?dl&keyword=pubg+qiwi&source=gmaps Pubg qiwi Looking to trade some of your PUBG Skins? If you are looking to open cases and crates, check out our...',
                              'url': 'https://www.google.com/maps/d/viewer?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa'}],
                 'metatags': [
                     {'og:image': 'https://www.google.com/maps/d/thumbnail?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa',
                      'og:type': 'website',
                      'twitter:card': 'summary_large_image',
                      'twitter:title': 'Pubg qiwi',
                      'viewport': 'initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width',
                      'twitter:description': 'Pubg qiwi → http://catomerra.rusmenik.ru/?dl&keyword=pubg+qiwi&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nPubg qiwi\n\nLooking to trade some of your PUBG Skins? If you are looking to open cases and crates, check out our list of the. Guess the winner color and return your bet multiplied by 2 or 14. Types of PUBG Gambling PUBG Roulette Roulette is a classic and pubg qiwi common casino game found on many gambling websites. Updates Check back on this page or pubg qiwi the application to see if a preset update is available. Some geospatial data on this website is provided by. You can customize your gaming experience to the fullest. Exchange your coins for whatever items you please. PUBGFair — DICE BONUS URL Have fun and win PUBGSkins by playing our dice game! This guide is not about making the game look good.\n\nAfter the two days of live PUBG, the winning team will be crowned! Visit our list of the where you can trade your PUBG skins and items fast and easy. Ingame settings can be quite tricky because it will perform different from',
                      'og:title': 'Pubg qiwi',
                      'og:url': 'https://www.google.com/maps/d/viewer?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa',
                      'og:description': 'Pubg qiwi → http://catomerra.rusmenik.ru/?dl&keyword=pubg+qiwi&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nPubg qiwi\n\nLooking to trade some of your PUBG Skins? If you are looking to open cases and crates, check out our list of the. Guess the winner color and return your bet multiplied by 2 or 14. Types of PUBG Gambling PUBG Roulette Roulette is a classic and pubg qiwi common casino game found on many gambling websites. Updates Check back on this page or pubg qiwi the application to see if a preset update is available. Some geospatial data on this website is provided by. You can customize your gaming experience to the fullest. Exchange your coins for whatever items you please. PUBGFair — DICE BONUS URL Have fun and win PUBGSkins by playing our dice game! This guide is not about making the game look good.\n\nAfter the two days of live PUBG, the winning team will be crowned! Visit our list of the where you can trade your PUBG skins and items fast and easy. Ingame settings can be quite tricky because it will perform different from',
                      'twitter:image:src': 'https://www.google.com/maps/d/thumbnail?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa'}],
                 'cse_image': [
                     {'src': 'https://www.google.com/maps/d/thumbnail?mid=17F5k_vXWgiurY7SWpEDEKuytN8kMBfXa'}]}},
            {'kind': 'customsearch#result',
             'title': 'Pubg mgn',
             'htmlTitle': '<b>Pubg</b> mgn',
             'link': 'https://www.google.com/mymaps/viewer?usp=sharing&mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM',
             'displayLink': 'www.google.com',
             'snippet': 'Pubg mgn => http://paycenriru.obzor-shop.ru/?dl&keyword=pubg+mgn&source=\ngmaps Pubg mgn Now you should see your FPS in-game go well above 144.',
             'htmlSnippet': '<b>Pubg</b> mgn =&gt; http://paycenriru.obzor-shop.ru/?dl&amp;keyword=<b>pubg</b>+mgn&amp;source=<br>\ngmaps <b>Pubg</b> mgn Now you should see your FPS in-game go well above 144.',
             'cacheId': 'iZZ0C5eyV1oJ',
             'formattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&mid...',
             'htmlFormattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&amp;mid...',
             'pagemap': {'cse_thumbnail': [{
                 'src': 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRTUwq4Plx2kktcF_eZ2FhKT53QZasD9wqquj-ecHeSbnPsxeH4AxOtKmHI',
                 'width': '225',
                 'height': '225'}],
                 'website': [
                     {'image': 'https://www.google.com/maps/d/thumbnail?mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM',
                      'name': 'Pubg mgn',
                      'description': 'Pubg mgn => http://paycenriru.obzor-shop.ru/?dl&keyword=pubg+mgn&source=gmaps Pubg mgn Now you should see your FPS in-game go well above 144. Usually overflowing with assault rifles and armor,...',
                      'url': 'https://www.google.com/maps/d/viewer?mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM'}],
                 'metatags': [{
                     'og:image': 'https://www.google.com/maps/d/thumbnail?mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM',
                     'og:type': 'website',
                     'twitter:card': 'summary_large_image',
                     'twitter:title': 'Pubg mgn',
                     'og:site_name': 'My Maps',
                     'viewport': 'initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width',
                     'twitter:description': 'Pubg mgn => http://paycenriru.obzor-shop.ru/?dl&keyword=pubg+mgn&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nPubg mgn\n\nNow you should see your FPS in-game go well above 144. Usually overflowing with assault rifles and armor, the bunkers are incredibly hazardous thanks to the wealth of choke points and narrow tunnels, most of which have no cover. Pubg mgn LAUNCH OPTIONS Open up Steam, and click on your Library. Feel free to comment if you have any questions. Leave a Reply Your email address will not be published. Pubg mgn school is a self-contained deathmatch area and a popular landing site for those who are confident in their abilities. This gives you a great opportunity to test the site before depositing your own PUBG skins. Looking for a PUBG Betting site? The Best PUBG Betting Sites All websites in our list is tested and approved by our staff. You have come to the right place! If you win you double up on your bet.\n\nUntil then we are unable to update stats on PUBG. Welcome to PUBG Network ARE YOU A PUBG PLAYER? So we recommend',
                     'og:title': 'Pubg mgn',
                     'og:url': 'https://www.google.com/maps/d/viewer?mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM',
                     'og:description': 'Pubg mgn => http://paycenriru.obzor-shop.ru/?dl&keyword=pubg+mgn&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nPubg mgn\n\nNow you should see your FPS in-game go well above 144. Usually overflowing with assault rifles and armor, the bunkers are incredibly hazardous thanks to the wealth of choke points and narrow tunnels, most of which have no cover. Pubg mgn LAUNCH OPTIONS Open up Steam, and click on your Library. Feel free to comment if you have any questions. Leave a Reply Your email address will not be published. Pubg mgn school is a self-contained deathmatch area and a popular landing site for those who are confident in their abilities. This gives you a great opportunity to test the site before depositing your own PUBG skins. Looking for a PUBG Betting site? The Best PUBG Betting Sites All websites in our list is tested and approved by our staff. You have come to the right place! If you win you double up on your bet.\n\nUntil then we are unable to update stats on PUBG. Welcome to PUBG Network ARE YOU A PUBG PLAYER? So we recommend',
                     'twitter:image:src': 'https://www.google.com/maps/d/thumbnail?mid=1UM9QnjMuWc0PsCS4DUUAX6H-l5mftYOM'}],
                 'cse_image': [{'src': 'https://khms0.googleapis.com/kh?v=770&hl=en&x=0&y=0&z=0'}]}},
            {'kind': 'customsearch#result',
             'title': 'Скачать игру pubg через торрент бесплатно',
             'htmlTitle': 'Скачать игру <b>pubg</b> через торрент бесплатно',
             'link': 'https://www.google.com/mymaps/viewer?usp=sharing&mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW',
             'displayLink': 'www.google.com',
             'snippet': 'Изначально все участники PUBG не имеют никакой экипировки и равны в \nсвоих возможностях. В них указаны минимальные характеристики, которыми\n\xa0...',
             'htmlSnippet': 'Изначально все участники <b>PUBG</b> не имеют никакой экипировки и равны в <br>\nсвоих возможностях. В них указаны минимальные характеристики, которыми<br>\n&nbsp;...',
             'cacheId': '9-s7dh0QAsMJ',
             'formattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&mid...',
             'htmlFormattedUrl': 'https://www.google.com/mymaps/viewer?usp=sharing&amp;mid...',
             'pagemap': {
                 'website': [{'image': 'https://www.google.com/maps/d/thumbnail?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW',
                              'name': 'Скачать игру pubg через торрент бесплатно',
                              'description': 'Скачать игру pubg через торрент бесплатно => http://fernberscamplin.prioms.ru/?dl&keyword=%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C+%D0%B8%D0%B3%D1%80%D1%83+pubg+%D...',
                              'url': 'https://www.google.com/maps/d/viewer?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW'}],
                 'metatags': [
                     {'og:image': 'https://www.google.com/maps/d/thumbnail?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW',
                      'og:type': 'website',
                      'twitter:card': 'summary_large_image',
                      'twitter:title': 'Скачать игру pubg через торрент бесплатно',
                      'viewport': 'initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width',
                      'twitter:description': 'Скачать игру pubg через торрент бесплатно => http://fernberscamplin.prioms.ru/?dl&keyword=%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C+%D0%B8%D0%B3%D1%80%D1%83+pubg+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+%D1%82%D0%BE%D1%80%D1%80%D0%B5%D0%BD%D1%82+%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nСкачать игру pubg через торрент бесплатно\n\nВ данном разделе вы не только сможете ознакомиться с детальным описанием каждой аркады, но и скачать понравившуюся игру через специальную ссылку на торрент. Все игры на сайте можно скачать полностью бесплатно и конечно же без регистрации. Перед тем, как выбрать одну из игр для взрослых, обратите внимание на ее детальное описан',
                      'og:title': 'Скачать игру pubg через торрент бесплатно',
                      'og:url': 'https://www.google.com/maps/d/viewer?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW',
                      'og:description': 'Скачать игру pubg через торрент бесплатно => http://fernberscamplin.prioms.ru/?dl&keyword=%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C+%D0%B8%D0%B3%D1%80%D1%83+pubg+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+%D1%82%D0%BE%D1%80%D1%80%D0%B5%D0%BD%D1%82+%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE&source=gmaps\n\n\n\n\n\n\n\n\n\n\n\nСкачать игру pubg через торрент бесплатно\n\nВ данном разделе вы не только сможете ознакомиться с детальным описанием каждой аркады, но и скачать понравившуюся игру через специальную ссылку на торрент. Все игры на сайте можно скачать полностью бесплатно и конечно же без регистрации. Перед тем, как выбрать одну из игр для взрослых, обратите внимание на ее детальное описан',
                      'twitter:image:src': 'https://www.google.com/maps/d/thumbnail?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW'}],
                 'cse_image': [
                     {'src': 'https://www.google.com/maps/d/thumbnail?mid=17haxbAKmWuwa_Q8Yi35VMm-yrawLviUW'}]}},
            {'kind': 'customsearch#result',
             'title': 'Make Money Online Through Website Monetization | Google ...',
             'htmlTitle': 'Make Money Online Through Website Monetization | Google ...',
             'link': 'https://www.google.com/intl/en_in/adsense/start/',
             'displayLink': 'www.google.com',
             'snippet': 'Learn how to make money online by pursuing your passion. We help you with \nwebsite and content monetization so you can make money while doing what you\n\xa0...',
             'htmlSnippet': 'Learn how to make money online by pursuing your passion. We help you with <br>\nwebsite and content monetization so you can make money while doing what you<br>\n&nbsp;...',
             'cacheId': '2jN7g2oZYe0J',
             'formattedUrl': 'https://www.google.com/intl/en_in/adsense/start/',
             'htmlFormattedUrl': 'https://www.google.com/intl/en_in/adsense/start/',
             'pagemap': {'cse_thumbnail': [{
                 'src': 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQp138p-ISLj5T2FDZPtfy8eYaCY1BEWZtfDS_uCo7rCye1MkaR9BHPYKU',
                 'width': '300',
                 'height': '168'}],
                 'metatags': [{'viewport': 'initial-scale=1, minimum-scale=1, width=device-width'}],
                 'cse_image': [
                     {'src': 'https://www.google.com/adsense/start/images/success/build-eazy-ss_2x.jpg'}]}},
            {'kind': 'customsearch#result',
             'title': 'Cyberpunk 2077: Release ist verschoben! - COMPUTER BILD SPIELE',
             'htmlTitle': 'Cyberpunk 2077: Release ist verschoben! - COMPUTER BILD SPIELE',
             'link': 'http://www.google.com/appserve/mkt/p/AL8lKjOtgF6hmv2OWr51qJWmQ4B0pMDBYihFoRAWyWbXitELm4OyV5QpN84fGqhOcFr3tLBPKzhAQI69CdzRgG4480waPrPdGUrVU755xgY7jDz3Gxdm3pnViEUbmZdYZmjISZ8KjTdTWqdsE_i5I1LGLuukFyJEhqLuhL-_oZ76LhlLPYB7b_pDX-CAOMcVrX3LOkl-62irlw',
             'displayLink': 'www.google.com',
             'snippet': '17. Jan. 2020 ... Entwickler CD Projekt Red verschiebt die Veröffentlichung seines \nRollenspielknallers „Cyberpunk 2077“. Hier die Gründe und der neue\xa0...',
             'htmlSnippet': '17. Jan. 2020 <b>...</b> Entwickler CD Projekt Red verschiebt die Veröffentlichung seines <br>\nRollenspielknallers „Cyberpunk 2077“. Hier die Gründe und der neue&nbsp;...',
             'cacheId': '1k_oSbtaIlcJ',
             'formattedUrl': 'www.google.com/.../ AL8lKjOtgF6hmv2OWr51qJWmQ4B0pMDBYihFoRAWyWbXitELm4Oy...',
             'htmlFormattedUrl': 'www.google.com/.../ AL8lKjOtgF6hmv2OWr51qJWmQ4B0pMDBYihFoRAWyWbXitELm4Oy...',
             'pagemap': {'cse_thumbnail': [{
                 'src': 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRTvVQ9p1p1JpN_5kqBTHwh-bwTBlXZt64vWRpI_hBVoWpOJ3Z52x2dKw8',
                 'width': '300',
                 'height': '168'}],
                 'imageobject': [{'width': '175',
                                  'url': 'https://i.computer-bild.de/i/newsletter/cb.png',
                                  'height': '80'},
                                 {'width': '658',
                                  'url': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk-2077-Artbook-658x370-74f2c419df55bc53.jpg',
                                  'height': '370'},
                                 {'width': '658',
                                  'url': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk-2077-658x370-573d474107373eea.jpg',
                                  'height': '370'},
                                 {'width': '658',
                                  'url': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk-2077-658x370-09cec6a009383355.jpg',
                                  'height': '370'},
                                 {'width': '658',
                                  'url': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk-2077-658x370-5472975b87376c9a.jpg',
                                  'height': '370'}],
                 'person': [{'name': 'Janina Carlsen'},
                            {'name': 'Udo Lewalter'},
                            {'name': 'Marco Häntsch'},
                            {'name': 'Manuel Bauer'},
                            {'name': 'Nico Jaenecke'},
                            {'name': 'Pavel Girard'}],
                 'review-aggregate': [{'votes': '438'}],
                 'organization': [{'name': 'COMPUTER BILD',
                                   'url': 'https://www.computerbild.de'}],
                 'rating': [{'average': '91', 'best': '100', 'worst': '0'}],
                 'metatags': [{
                     'og:image': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk_2077-bfea47143fca767d.jpg',
                     'twitter:card': 'summary',
                     'fb:app_id': '188313526894',
                     'og:type': 'article',
                     'twitter:site': '@COMPUTERBILD',
                     'og:site_name': 'computerbild.de',
                     'og:title': 'Cyberpunk 2077: Gameplay, Release, Trailer – alles zum Rollenspiel!',
                     'og:locale': 'de_DE',
                     'og:url': 'https://www.computerbild.de/artikel/cbs-News-Cyberpunk-2077-Termin-7540863.html',
                     'fb:pages': '185789627834',
                     'og:description': 'Fans müssen jetzt ganz stark sein: Der polnische Spieleentwickler CD Projekt Red verschiebt seinen Rollenspielknaller „Cyberpunk 2077“. Hier die Gründe und der neue Release-Termin!'}],
                 'creativework': [
                     {'name': 'Cyberpunk 2077: Gameplay, Release, Trailer – alles zum Rollenspiel!'}],
                 'cse_image': [{
                     'src': 'https://i.computer-bild.de/imgs/4/3/7/3/8/6/4/Cyberpunk_2077-bfea47143fca767d.jpg'}],
                 'article': [{
                     'articlebody': "Cyberpunk 2077752K subscribersSubscribeCyberpunk 2077 – Deep Dive VideoWatch laterShareCopy linkInfoShoppingTap to unmuteIf playback doesn't begin shortly, try restarting your device.More...",
                     'datemodified': '2020-01-17T16:20:00+01:00',
                     'description': 'Fans müssen jetzt ganz stark sein: Der polnische Spieleentwickler CD Projekt Red verschiebt seinen Rollenspielknaller „Cyberpunk 2077“. Hier die Gründe und der neue Release-Termin!',
                     'headline': 'Cyberpunk 2077: Gameplay, Release, Trailer – alles zum Rollenspiel!',
                     'datepublished': '2016-08-30T07:22:00+02:00'}]}}]
    req_params = {
        'key': SEARCH_API_KEY,
        'cx': SEARCH_ENGINE_ID,
        'q': search_term,
    }
    final_req_params = {**req_params, **{'num': kwargs.get('num', 10)}, **kwargs}
    result = requests.get(url=search_url, params=final_req_params)
    print(result)
    return result.json().get('items')
